### PR TITLE
use Toml 6.0.0

### LINKED ISSUE #231: Comby fails to build with toml 6.0.0
I followed the instruction in README, and I got:

```
$ make
dune build --profile dev
File "lib/configuration/command_configuration.ml", line 122, characters 11-20:
122 |   let open TomlTypes in
                 ^^^^^^^^^
Error: Unbound module TomlTypes
```

Build succeeds after `opam pin add toml 5.0.0`.

### PR DESCRIPTION
**Pull request by rvantonder**
Fixes #231

### CODE REVIEW

**Comment by rvantonder** [comment]
Closed in favor of #234
