### ISSUE TITLE
Comby fails to build with toml 6.0.0

### ISSUE THREAD

**Issue by sanxiyn** [comby-tools/comby#231]
I followed the instruction in README, and I got:

```
$ make
dune build --profile dev
File "lib/configuration/command_configuration.ml", line 122, characters 11-20:
122 |   let open TomlTypes in
                 ^^^^^^^^^
Error: Unbound module TomlTypes
```

Build succeeds after `opam pin add toml 5.0.0`.

**Comment by rvantonder** [comment]
Thanks for the heads up, will update so things work with Toml 6.0.0.

**Comment by rvantonder** [comment]
Should be fixed now, thanks again.
